spring:
  profiles: local
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:30000/postgres
    platform: postgres
    driver-class-name: org.postgresql.Driver
    password: test123
    username: postgres
    hikaki:
      maximum-pool-size: 20
      schema: measurements
server:
  port: 8080
de:
  heinze:
    kafka:
      connectionURL: thisIsAConnectionURL
      broker-address: brokerAddress1
      number-of-brokers: 5
      consumer:
        consumer-string: SpecialConsumerString

